name: Deployment Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::737032216196:role/website-github-actions
          aws-region: eu-west-1
      - name: Test AWS credentials
        run: |
          aws sts get-caller-identity
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.7
          terraform_wrapper: false
      - name: Deploy Terraform
        run: |
          echo "$AWS_ACCESS_KEY_ID"
          echo "$AWS_SECRET_ACCESS_KEY"
          cd infrastructure/terraform && terraform init && terraform apply -auto-approve 

