name: Deployment Pipeline
    on:
      push:
        branches:
          - main
    jobs:
      build-and-deploy:
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: 1.2.9
              terraform_wrapper: false
          - name: Deploy Terraform
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            run: cd terraform && terraform init && terraform apply -auto-approve
            run: cd terraform && terraform init && terraform apply -auto-approve

